<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Actived' => 'Attivato',
    'All Users' => 'Tutti gli Utenti',
    'Avatar' => 'Avatar',
    'Birthday' => 'Data di Nascita',
    'By clicking I Agree, you agree to the Terms and Conditions set out by this site, including our Cookie Use.' => 'Mettando la spunta, accetti tutti e Termini e le Condizioni del sito, incluso l\'uso dei Cookie',
    'Captcha' => 'Codice di Sicurezza',
	'Change Avatar' => 'Cambia Avatar',
	'Delete Success!' => 'Cancellazione eseguita con successo!',
    'Enabled' => 'Abilitato',
    'Firstname' => 'Nome',
    'I Agree' => 'ACCONSENTO',
	'ID' => 'ID',
	'In order to finish your registration, we need you to enter following fields' => 'Per completare la registrazione, inserisci i campi seguenti',
	'Incorrect Username or Password' => 'Username o Password non validi',
    'Lastname' => 'Cognome',
    'Last login' => 'Ultimo Login',
    'Last Users' => 'Ultimi Utenti',
    'Login successful' => 'Login effettuato con successo',
    'Manage permissions' => 'Gestione Permessi',
    'Manage roles' => 'Gestione Ruoli',
    'Manage users' => 'Gestione Utenti',
    'Name' => 'Nome Utente',
    'Never' => 'Mai',
    'New' => 'Nuovo',
    'New User' => 'Nuovo Utente',
	'Public Email' => 'Email Pubblica',
	'Register' => 'Registrati',
	'Registration' => 'Registrazione',
    'Reset' => 'Annulla',
	'Role' => 'Ruolo',
	'Roles' => 'Ruoli',
    'Select at least one item' => 'Seleziona almeno 1 elemento!',
    'Select only 1 item' => 'Seleziona solo 1 elemento!',
	'Select role' => 'Ruolo ...',
	'Signature' => 'Firma',
	'Type your credentials' => 'Inserisci le tue credenziali',
    'Update' => 'Modifica',
	'You must agree to the terms and conditions' => 'Devi accettare Termini&Condizioni',
];
